// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/simple/douyin/cmd/publish/rpc"
)

func Init() {
	rpc.InitRPC()
}

func main() {
	Init()
	h := server.New(
		server.WithHostPorts(":8080"),
		server.WithHandleMethodNotAllowed(true), // coordinate with NoMethod
	)

	register(h)
	h.Spin()
}
